server:
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    ingressClassName: "alb"

configs:
  params:
    server.insecure: true
